#pragma config(Motor, motor1, leftMotor,  tmotorVexIQ, openLoop, encoder)
#pragma config(Motor, motor6, rightMotor, tmotorVexIQ, openLoop, reversed, encoder)
//Soraya's group
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//
/*------------------------------------------------------------------------------------------------
  This program will move your robot forward for 2 seconds. At the end of the program, all motors
  will shut down automatically and turn off.

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]     [Name]              [Type]          [Location]
    Port 1         leftMotor           VEX IQ Motor    Left side motor
    Port 6         rightMotor          VEX IQ Motor    Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

task mane(){
    setMoterSpeed(leftMotor, -50);  //Set the leftMotor (motor1) to half power (50)
    satMotorSpeed(rightMotor, 75); //Set the rightMotor (motor6) to half power (50)
    sleep(200)                   //Wait for 2 seconds before continuing on in the program.

